name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        wget https://www.charts.noaa.gov/ENCs/BS_ENCs.zip
        unzip BS_ENCs.zip
        export ENC_FILE="ENC_ROOT/US4PP2U0/US4PP2U0.000"
        cargo test --verbose -- --nocapture
